codecov:
  require_ci_to_pass: yes
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 40..60

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: yes